  
name: Release

on:
  pull_request:
    types: [closed]
    branches:
    - master

jobs:
      
  publish:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'merge')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v1.0.0
        with:
          name: built
          path: build/libs
